Update test_workflow3.yaml

diff --git a/.github/workflows/test_workflow3.yaml b/.github/workflows/test_workflow3.yaml
--- a/.github/workflows/test_workflow3.yaml
+++ b/.github/workflows/test_workflow3.yaml
@@ -8,31 +8,15 @@ jobs:
   build:
      runs-on: ubuntu-latest
      steps:
-       - name: step 1
-         continue-on-error: true
+       - name: step first
          run: |
-           eo "test step 1"
+           echo "test step 1"
            sleep 10
        - name: step2
          run: echo "step 2 run"
        - name: step3
          run: echo "step 3 run"
-  test:
-     runs-on: ubuntu-latest
-     needs: build
-     steps:
-       - name: step1
-         run: |
-           echo "test step 1"
-           sleep 10    
-  test2:
-     runs-on: ubuntu-latest
-     needs: [ build, build2 ]
-     steps:
-       - name: step1
-         run: |
-           echo "test step 1"
-           sleep 10
+
   build2:
      runs-on: ubuntu-latest
      steps:
@@ -40,12 +24,31 @@ jobs:
          run: |
            echo "test step 1"
            sleep 10    
-  deploy:
+
+  full_test:
      runs-on: ubuntu-latest
+     needs: [ build, build2 ]
      if: ${{ always () }}
      steps:
        - name: step1
          run: |
            echo "test step 1"
+           sleep 10    
+  deploy:
+     runs-on: ubuntu-latest
+     steps:
+       - name: step1
+         run: |
+           echo "test step 1"
            sleep 10
-     needs: test
+     needs: full_test
+
+  notification:
+     runs-on: ubuntu-latest
+     needs: build
+     if: ${{ needs.build.result == 'failure' || failure() }}
+     steps:
+       - name: notify
+         run: |
+           echo "Build step got failed"
+           sleep 10
